/*

 BALL1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TileLabelBank 0
/* Start of tile array. */
<<<<<<< HEAD
extern unsigned char ball1[];
=======
const extern unsigned char TileLabel[];
>>>>>>> e6443eed3354cf5d50e90611b869619c8a610b0f

/* End of BALL1.H */
