/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 26 x 16
   Tile set      : stadium.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 26
#define mapHeight 16
#define mapBank 0

extern unsigned char map[];

/* End of MAP.H */
